modLoader="javafml"
loaderVersion="[61,)"
license="MIT"
[[mods]]
modId="regionlib"
version="1.0.0"
displayName="Region Library"
authors="Fealtous"
displayTest="IGNORE_SERVER_VERSION" # We have no client component
description='''
A library mod for detecting changes to regions of the world. Configurable specificity.
Depends on MinecraftForge for the purposes of compatibility and configurability.
Inspired by MCMMO's system, but doesn't go so far as to reimplement region files.'''

[[dependencies.regionlib]]
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.regionlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,1.21.12)"
    ordering="NONE"
    side="BOTH"
